### ISSUE TITLE
Mock data it is possible?

### ISSUE THREAD

**Issue by sefirosweb** [faebeee/storybook-axios#3]
Hello! 

In my project i have a axios mock data, for local testsing and preview of app withouth real endpoints

I'm trying to add your pluging into preview of "fake" result of mock but cant see nothing results

If it possible you can add a small examle?
SImilar has:
```js
// get-axios.js
import axios from 'axios';
import MockAdapter from 'axios-mock-adapter'

const instance = axios.create();
export const getAxios = () => instance;

const TIMEOUT = 600

const mock = new MockAdapter(axios, {
    onNoMatch: 'passthrough',
    delayResponse: TIMEOUT,
})

const createData = () => {
    return [ 'asd','asd2']
}

const generateDataSubtable = () => {
    return new Promise(function (resolve) {
        const data = createData()
        resolve([
            200,
            {
                success: true,
                data,
            },
        ])
    })
}

mock.onGet('/api/').reply(() => {
    console.log(`Axios request: '/api/sub_table' GET`)
    return generateDataSubtable()
})
```

**Comment by faebeee** [comment]
Thats because (my guess) there are no requests coming to axios itself. The are captured by the mock adapter

**Comment by sefirosweb** [comment]
@faebeee  finally i got it :D 🥇 

fyi:

```ts
// mock_file.ts

import { faker } from '@faker-js/faker';
import axios, { AxiosRequestConfig, AxiosResponse } from 'axios'
import MockAdapter from 'axios-mock-adapter'

const TIMEOUT = 600

const mock = new MockAdapter(axios, { onNoMatch: 'passthrough', delayResponse: TIMEOUT });

mock.onGet('/api/').reply(() => {
    console.log(`Axios request: '/api/sub_table' GET`)
    return generateDataSubtable()
})
...
```ts
// preview.ts
import axios from "axios";
import withAxiosDecorator from 'storybook-axios';
import './dataMock';

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
}

export const decorators = [withAxiosDecorator(axios)];
```

For my case I must dont use a create instance, i inject into axios directly 

Of course network is empty but your pluging detects him =)

![image](https://user-images.githubusercontent.com/20754836/204567455-f61bf1d3-0f67-4588-9221-f97014ff52fc.png)

Another question i have small warning but this warning happens with instance or axios static object, but works fine 

![image](https://user-images.githubusercontent.com/20754836/204567631-ed7e49dc-7dec-46ca-ba59-562fac84eef4.png)

Note: soon I will upload to main branch, if you want to take a look of full code:
https://github.com/sefirosweb/react-crud/tree/master/.storybook

**Comment by faebeee** [comment]
Very Nice 👍
